name: AscensionBingo
version: '1.0'
main: me.depickcator.ascensionBingo.AscensionBingo
api-version: '1.21'
commands:
  open-main-menu:
    description: This command open the main menu
  give-main-menu:
    description: This command gives the main menu item
  game:
    description: Allows to access the main game states
  changeBingoScore:
    description: changes the bingo score for a certain player
  openmenu:
    description: opens all menu in the main menu via command
  party:
    description: team up with other players
  printPlayerData:
    description: prints the player Data
  unlockCraft:
    description: unlocks a craft for a certain player
  setUnlockTokens:
    description: testing purposes only
  givePlayerExp:
    description: testing purposes only
