name: Ascension
version: '1.0'
main: me.depickcator.ascension.Ascension
api-version: '1.21'
commands:
  open-main-menu:
    description: This command open the main menu
  give-main-menu:
    description: This command gives the main menu item
    permission: ascension.give-main-menu
  openmenu:
    description: opens all menu in the main menu via command
  party:
    description: team up with other players
  shout:
    description: allows players to communicate with the entire server
  queue:
    description: queue
  printWorldInfo:
    description: prints the world information

  game:
    description: Allows to access the main game states
    permission: ascension.game
  changeBingoScore:
    description: changes the bingo score for a certain player
    permission: ascension.changeBingoScore
  debugger:
    description: turns on and off the debugger
    permission: ascension.debugger
  timeline:
    description: sets timeline
    permission: ascension.timeline
  setUnlockTokens:
    description: testing purposes only
    permission: ascension.setUnlockTokens
  givePlayerExp:
    description: testing purposes only
    permission: ascension.givePlayerExp
  startEvent:
    description: testing purposes only
    permission: ascension.startEvent
  giveCustomItem:
    description: testing purposes only
    permission: ascension.startEvent
